#pragma once
#include <object/base_obj.h>
#include <object/bool_obj.h>
#include <object/break_obj.h>
#include <object/builtin_method.h>
#include <object/builtin_obj.h>
#include <object/continue_obj.h>
#include <object/error_obj.h>
#include <object/float_obj.h>
#include <object/function_obj.h>
#include <object/hash_obj.h>
#include <object/hashable.h>
#include <object/hashkeys_obj.h>
#include <object/hashpair_obj.h>
#include <object/hashvalues_obj.h>
#include <object/integer_obj.h>
#include <object/iterable.h>
#include <object/list_obj.h>
#include <object/null_obj.h>
#include <object/return_obj.h>
#include <object/string_obj.h>
#include <object/type_obj.h>