#pragma once
#include <ast/assign.h>
#include <ast/block.h>
#include <ast/bool.h>
#include <ast/break.h>
#include <ast/call.h>
#include <ast/case.h>
#include <ast/compound_assign.h>
#include <ast/continue.h>
#include <ast/expression_statement.h>
#include <ast/float.h>
#include <ast/for.h>
#include <ast/function.h>
#include <ast/hash.h>
#include <ast/identifier.h>
#include <ast/if.h>
#include <ast/in.h>
#include <ast/index.h>
#include <ast/infix.h>
#include <ast/integer.h>
#include <ast/list.h>
#include <ast/method.h>
#include <ast/node.h>
#include <ast/null.h>
#include <ast/postfix.h>
#include <ast/prefix.h>
#include <ast/program.h>
#include <ast/property.h>
#include <ast/return.h>
#include <ast/scenario.h>
#include <ast/string.h>
#include <ast/switch.h>
#include <ast/ternary.h>
#include <ast/while.h>